FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

COPY whisper_service/requirements.txt .
# Ensure whisper-cpp-python is not installed
RUN sed -i '/whisper-cpp-python/d' requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY whisper_service/ .

EXPOSE 8002

CMD ["python", "server.py"]
